### ISSUE TITLE
Метод поиска игры по жанру в классе Player не возвращает игру

### ISSUE THREAD

**Issue by Dina18013** [Valted-cmd/TeamWork#1]
# Описание
Метод поиска игры по жанру, в которую играли больше всего, не возвращает игру этого жанра.

# Локация дефекта
https://github.com/Valted-cmd/TeamWork/blob/main/src/main/java/ru/netology/Player.java

# Шаги воспроизведения
1.Открыть [код программы](https://github.com/Valted-cmd/TeamWork) на GitHub
2.Открыть класс Player https://github.com/Valted-cmd/TeamWork/blob/main/src/main/java/ru/netology/Player.java
3.Сравнить описание метода поиска игры, в которую играли больше всего, с его реализацией

*Ожидаемый результат:*Метод возвращает: return mostPlayerByGenre; return null;
*Фактический результат:*Метод возвращает только: return null;

# Скриншот
https://github.com/Valted-cmd/TeamWork/blob/7c77a54c6508cca0b072ed86ecd6085013e16944/src/main/java/ru/netology/Player.java#L57-L61

# Окружение
* **Операционная система:** Windows10 21H2
*  **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
*  **JAVA:** OpenJDK 11

**Comment by Valted-cmd** [comment]
**Отчет по баг-репорту**

Баг исправил.
Метка метода: 

https://github.com/Valted-cmd/TeamWork/blob/b8f75cadbf645a51f5c199eac08af2b03cd0337b/src/main/java/ru/netology/Player.java#L59

**Скриншот**
![0](https://user-images.githubusercontent.com/67290277/170522931-6b8ad1d8-f98d-4852-898e-af933ef9fced.png)
