### ISSUE TITLE
Неверное суммирование времени, проведенного в ОДНОЙ игре жанра

### ISSUE THREAD

**Issue by Dina18013** [Valted-cmd/TeamWork#11]
# Описание
Метод sumGenre класса Player не суммирует время по жанру, проведенное в одной игре. Выводит нулевой результат.

# Локация дефекта
https://github.com/Valted-cmd/TeamWork/blob/main/src/main/java/ru/netology/Player.java

# Шаги воспроизведения
В тестовом методе:
​1. Создать объект класса Player;
2. Создать объект класса Game;
3. Вызвать метод installGame объекта Player, передать в него объект класса Game (созданную игру);
4. Вызвать метод play объекта Player, передать в него ранее созданную игру и время (в примере - 3 часа);
5. Вызвать метод sumGenre объекта Player, передать в него жанр ранее созданной игры;
6. Отладить метод.

*Ожидаемый результат:* Вывод метода sumGenre - 3.
*Фактический результат:* Вывод метода sumGenre - 0.

# Скриншот
![work1](https://user-images.githubusercontent.com/99754434/171916158-bcde07db-4416-4d1b-bcb2-953f2bcff8ad.png)

# Окружение
* **Операционная система:** Windows10 21H2
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Valted-cmd** [comment]
### **Отчет по баг-репорту**

Баг исправлен.

**Скриншот теста.**
![11](https://user-images.githubusercontent.com/67290277/171921538-eec0555a-8bb2-4ff9-a646-6dbd79e8de29.PNG)
