### ISSUE TITLE
Не выводится популярная игра жанра из ДВУХ и БОЛЕЕ игр при неравном времени в игре

### ISSUE THREAD

**Issue by Dina18013** [Valted-cmd/TeamWork#12]
# Описание
В результате работы метода mostPlayerByGenre после установки нескольких игр одного жанра возвращается NULL вместо игры, в методе play на которую было передано бОльшее время.

# Локация дефекта
https://github.com/Valted-cmd/TeamWork/blob/main/src/main/java/ru/netology/Player.java

# Шаги воспроизведения
В тестовом методе:
​
1. Создать объект класса Player;
2. Создать два или более объекта класса Game (на примере двух игр: game1, game2; трех - game1, game2, game3);
3. Два или более раза вызвать метод installGame объекта Player, передать в него поочередно ранее созданные объекты класса Game;
4. Два или более раза вызвать метод play объекта Player, передать в него поочередно созданные игры и время (в примере для двух игр: 5 и 3 часа; в примере для трех игр - 4, 5, 6 часов);
5. Вызвать метод mostPlayerByGenre объекта Player, передать в него жанр ранее созданных игр (в примере - "Хоррор");
6. Отладить метод.

*Ожидаемый результат:* Возвращаемое значение метода mostPlayerByGenre - game1 (при двух играх) / game3 (при трех играх).
*Фактический результат:* Возвращаемое значение метода mostPlayerByGenre - NULL.
 
# Скриншот
![work4](https://user-images.githubusercontent.com/99754434/171924699-7a5d78c3-824c-491c-b81d-610f6660c71d.png)
![work5](https://user-images.githubusercontent.com/99754434/171924957-796670c6-80fa-4115-99d6-c53f857ae0e0.png)

# Окружение
* **Операционная система:** Windows10 21H2
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Valted-cmd** [comment]
### **Отчет по баг-репорту**

**Метка метода**

https://github.com/Valted-cmd/TeamWork/blob/be0174828789405f59cd5d84ed56e9ffb50c34c4/src/main/java/ru/netology/Player.java#L71

Баг исправлен, тест проходит

**Скриншоты теста**
![12](https://user-images.githubusercontent.com/67290277/171929154-c13ef4b7-4392-40c5-82c0-d741e71e7118.PNG)
![13](https://user-images.githubusercontent.com/67290277/171929174-f155e34b-be80-4725-b25e-c76337ede2c0.PNG)
