### ISSUE TITLE
Неверное суммирование времени, проведенного в ДВУХ и БОЛЕЕ играх одного жанра

### ISSUE THREAD

**Issue by Dina18013** [Valted-cmd/TeamWork#13]
# Описание
Метод sumGenre класса Player неверно суммирует время, проведенное в двух и более играх. Вместо суммы метод выводит 0.

# Локация дефекта
https://github.com/Valted-cmd/TeamWork/blob/main/src/main/java/ru/netology/Player.java

# Шаги воспроизведения
В тестовом методе:
​
1. Создать объект класса Player;
2. Создать два или более объекта класса Game с одинаковым жанром;
3. Два или более раза вызвать метод installGame объекта Player, передать в них поочередно объекты класса Game (созданные игру);
4. Два или более раза вызвать метод play объекта Player, передать в него поочередно ранее созданные игры и время (в примере с двумя играми: 3 и 5; с тремя - 3, 5, 5);
5. Вызвать метод sumGenre объекта Player, передать в него жанр ранее созданных игр;
6. Отладить метод.

*Ожидаемый результат* Вывод метода sumGenre по двум играм из примера - 8.
По трем играм из примера - 13.
​*Фактический результат* Вывод метода sumGenre - 0.

# Скриншот
![work6](https://user-images.githubusercontent.com/99754434/171926225-4a754844-dd2e-4724-977c-7d8f30d0e4f1.png)
![work7](https://user-images.githubusercontent.com/99754434/171926456-c8314933-4862-491e-958b-97f8380602d2.png)

# Окружение
* **Операционная система:** Windows10 21H2
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Valted-cmd** [comment]
### **Отчет по баг-репорту**

**Метка кода**
https://github.com/Valted-cmd/TeamWork/blob/d5b1ff6fa938935654b31e077353a4bce672f314/src/main/java/ru/netology/Player.java#L55

Баг исправлен, тест проходит.

**Скриншоты теста**
![14](https://user-images.githubusercontent.com/67290277/171931612-68cefacd-cbbf-468a-a19f-3b897e0f7371.PNG)
![15](https://user-images.githubusercontent.com/67290277/171931624-f404212c-0bca-4b27-aaa9-64e728414428.PNG)

**Comment by Valted-cmd** [comment]
При коммите не ту цифру поставил, не "13" должно быть, а "16"))
