### ISSUE TITLE
Не выбрасывается Runtime Exception при вызове метода play на неустановленную игру

### ISSUE THREAD

**Issue by Dina18013** [Valted-cmd/TeamWork#14]
# Описание
При вызове метода play и передаче в него объекта класса Game БЕЗ предварительного вызова метода installGame на объект игры НЕ выкидывается исключение Runtime Exception.

# Локация дефекта
https://github.com/Valted-cmd/TeamWork/blob/main/src/main/java/ru/netology/Player.java

# Шаги воспроизведения
В тестовом методе:
​
1. Создать объект класса Player;
2. Создать объект класса Game;
3. Вызвать метод play объекта Player, передать в него объект Game и время (в примере - 5);
4. Отладить метод.

*Ожидаемый результат* Вывод исключения Runtime Exception, завершение программы.
​*Фактический результат* Runtime Exception не выкидывается.

# Скриншот
![work8](https://user-images.githubusercontent.com/99754434/171930662-ba68074e-9f75-4aa6-b38f-4bd91f14c754.png)

# Окружение
* **Операционная система:** Windows10 21H2
* **IDE: IntelliJ IDEA 2021.3.2** (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Valted-cmd** [comment]
### **Отчет по баг-репорту**

**Метка кода**
https://github.com/Valted-cmd/TeamWork/blob/d5b1ff6fa938935654b31e077353a4bce672f314/src/main/java/ru/netology/Player.java#L39

Баг исправил, тест проходит

**Скриншоты теста**
![11](https://user-images.githubusercontent.com/67290277/171933073-e18eb31e-565b-4138-8f54-faf11f4ffada.PNG)
