### ISSUE TITLE
Не суммируется время, проведенное в игре за ОДИН подход

### ISSUE THREAD

**Issue by Dina18013** [Valted-cmd/TeamWork#15]
# Описание
Результат работы единоразового вызова метода play объекта класса Player с переданным в него временем возвращает нулевое значение вместо времени, которое было передано.

# Локация дефекта
https://github.com/Valted-cmd/TeamWork/blob/player/src/test/java/ru/netology/PlayerTest.java

# Шаги воспроизведения

1. Создать объект класса Player;
2. Создать объект класса Game;
3. Вызвать метод installGame объекта Player, передать в него объект класса Game (созданную игру);
4. Вызвать метод play объекта Player, передать в него игру и время (в примере - 5);
5. Отладить метод.

*Ожидаемый результат* Возвращаемое значение метода play - 5.
*Фактический результат* Возвращаемое значение метода play - 0.

# Скрин
![work9](https://user-images.githubusercontent.com/99754434/171941062-33a35c9a-276b-4579-990b-b25ba68fb848.png)

# Окружение
* **Операционная система:** Windows10 21H2
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

​

**Comment by Valted-cmd** [comment]
### **Отчет по баг-репорту**

**Метка кода**

https://github.com/Valted-cmd/TeamWork/blob/d5b1ff6fa938935654b31e077353a4bce672f314/src/main/java/ru/netology/Player.java#L39

Баг исправлен, тест проходит

**Скриншоты теста**

![11](https://user-images.githubusercontent.com/67290277/171942832-9c95e6ac-1e42-43f8-977e-0abe028792a7.PNG)
