### ISSUE TITLE
После переустановки игры обнуляется время, проведенное в игре

### ISSUE THREAD

**Issue by Dina18013** [Valted-cmd/TeamWork#16]
# Описание
При переустановке игры (последовательный вызов installGame, play(), installGame) обнуляется переданное в метод play время. !!!Баг сопряжен с багом метода sumGenre.
​
# Локация дефекта
https://github.com/Valted-cmd/TeamWork/blob/player/src/test/java/ru/netology/PlayerTest.java

# Шаги воспроизведения
В тестовом методе:
​
1.Создать объект класса Player;
2. Создать объект класса Game;
3. Вызвать метод installGame объекта Player, передать в него объект класса Game (созданную игру);
4. Вызвать метод play объекта Player, передать в него игру и время (в примере - 4);
5. Повторно вызвать метод installGame объекта Player, передать в него ту же игру.
6. Проверить сохраненное время вызовом метода sumGenre по жанру игры.

*Ожидаемый результат* Возвращаемое значение метода play - 4.
​*Фактический результат* Возвращаемое значение метода play - 0.

# Скриншот
![work10](https://user-images.githubusercontent.com/99754434/171942652-52d91469-557e-4c8b-bc5b-a231191c9326.png)

# Окружение
* **Операционная система:** Windows10 21H2
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Valted-cmd** [comment]
### **Отчет по баг-репорту**

**Метка кода**

https://github.com/Valted-cmd/TeamWork/blob/96914681293e281d34e05a0efdd46b1c76131582/src/main/java/ru/netology/Player.java#L28

Баг исправил, тест проходит

**Скриншот теста**

![11](https://user-images.githubusercontent.com/67290277/171946050-ba66fa6c-134e-4f3e-8334-8fa8a8321d9e.PNG)
