### ISSUE TITLE
Поиск заигравшегося игрока выдает неправильное значение, когда игроки играли по 0-1 часа

### ISSUE THREAD

**Issue by Valted-cmd** [Valted-cmd/TeamWork#3]
# **Метка метода**

https://github.com/Valted-cmd/TeamWork/blob/7c77a54c6508cca0b072ed86ecd6085013e16944/src/main/java/ru/netology/GameStore.java#L58

# **Метка тестового метода**

https://github.com/Valted-cmd/TeamWork/blob/5acc4910af02b1919120c59f9a0bac290c780ad1/src/test/java/ru/netology/GameStoreTest.java#L111

# **Описание**
Метод getMostPlayer класса GameStore возвращает неправильный результат, когда игроки играли по 0-1 часов

# **Шаги воспроизведения**
В тестовом методе:

1. Создать объект класса GameStore ;
2. Вызвать несколько раз метод addPlayTime объекта GameStore, передать в него необходимые параметры: разные имена игроков и от 0 до 1 часов, потраченных на игры;
3. Вызвать метод getMostPlayer объекта GameStore;

# **Ожидаемый результат**
Вывод метода getMostPlayer - имя первого игрока на шаге 2, который играл 1 час ("Psycho").

# **Фактический результат**
Вывод метода getMostPlayer - null.

# **Скриншот**

![Скриншот 2](https://user-images.githubusercontent.com/67290277/170508562-0a065bb1-b711-4ec4-9396-914a4108160a.png)

# **Окружение**

Windows 10
IntelliJ IDEA 2021.3.2 (Community Edition)

**Comment by Dina18013** [comment]
# Метка кода
 [https://github.com/Valted-cmd/TeamWork/blob/328e03e042b8a721e8855d16a119a70b81af671d/src/main/java/ru/netology/GameStore.java#L58](url)

Баг исправила. Тест проходит.
# Скриншот теста
![work11](https://user-images.githubusercontent.com/99754434/171953073-e43b7bee-10fa-4a84-aab1-6be800c20939.png)
