### ISSUE TITLE
Неправильно работает проверка наличия игры в каталоге для последней добавленной игры

### ISSUE THREAD

**Issue by Valted-cmd** [Valted-cmd/TeamWork#4]
# **Метка метода**

https://github.com/Valted-cmd/TeamWork/blob/0e90f32faa99a1240e14cbc4bfb145c1ff951422/src/main/java/ru/netology/GameStore.java#L32

# **Метка тестового метода**

https://github.com/Valted-cmd/TeamWork/blob/5acc4910af02b1919120c59f9a0bac290c780ad1/src/test/java/ru/netology/GameStoreTest.java#L41

# **Описание**
Метод containsGame класса GameStore возвращает неправильный результат для последней добавленной игры

# **Шаги воспроизведения**
В тестовом методе:

1. Создать объект класса GameStore ;
2. Вызвать несколько раз метод publishGame объекта GameStore, передать в него необходимые параметры для создания игр;
3. Вызвать метод containsGame объекта GameStore, передать в него последнюю игру, созданную на шаге 2;

# **Ожидаемый результат**
Вывод метода containsGame - true.

# **Фактический результат**
Вывод метода containsGame - false.

# **Скриншот**
![Crhbyijn 3](https://user-images.githubusercontent.com/67290277/170511008-a663f326-2a5d-4eba-a134-f877cc4fdd9c.png)

# **Окружение**

Windows 10
IntelliJ IDEA 2021.3.2 (Community Edition)

**Comment by Dina18013** [comment]
# Метка метода
[https://github.com/Valted-cmd/TeamWork/blob/b5f4f0930ad6fdfd2e629f683dcd1614e5a836e3/src/main/java/ru/netology/GameStore.java#L31](url)

Баг исправила. Тест проходит.
# Скриншот теста
![work12](https://user-images.githubusercontent.com/99754434/171994859-e1cc2b17-038c-4c3d-8c48-39ea65b2725d.png)
