### ISSUE TITLE
Неправильно работает проверка наличия игры в каталоге, если, в каталог добавлена только одна игра.

### ISSUE THREAD

**Issue by Valted-cmd** [Valted-cmd/TeamWork#5]
# **Метка метода**
https://github.com/Valted-cmd/TeamWork/blob/5acc4910af02b1919120c59f9a0bac290c780ad1/src/main/java/ru/netology/GameStore.java#L32

# **Метка тестового метода**
https://github.com/Valted-cmd/TeamWork/blob/5acc4910af02b1919120c59f9a0bac290c780ad1/src/test/java/ru/netology/GameStoreTest.java#L13

# **Описание**
Метод containsGame класса GameStore возвращает неправильный результат при наличии в каталоге только одной игры

# **Шаги воспроизведения**
В тестовом методе:

1. Создать объект класса GameStore ;
2. Вызвать метод publishGame объекта GameStore, передать в него необходимые параметры для создания игры;
3. Вызвать метод containsGame объекта GameStore, передать в него игру, созданную на шаге 2;

# **Ожидаемый результат**
Вывод метода containsGame - true.

# **Фактический результат**
Вывод метода containsGame - false.

# **Скриншот**
![одна игра](https://user-images.githubusercontent.com/67290277/170513026-15e32c3f-adf7-4b7b-b807-b949a5bc37f7.png)

# **Окружение**

Windows 10
IntelliJ IDEA 2021.3.2 (Community Edition)

**Comment by Dina18013** [comment]
# Метка метода
[https://github.com/Valted-cmd/TeamWork/blob/b5f4f0930ad6fdfd2e629f683dcd1614e5a836e3/src/main/java/ru/netology/GameStore.java#L31](url)

Баг исправила. Тест проходит.

# Скриншот
![work13](https://user-images.githubusercontent.com/99754434/171995441-30a337ef-c5fc-4040-8008-9f37d2f37542.png)
