### ISSUE TITLE
Не происходит суммирования игрового времени для конкретного игрока

### ISSUE THREAD

**Issue by Valted-cmd** [Valted-cmd/TeamWork#6]
# **Метка метода**
https://github.com/Valted-cmd/TeamWork/blob/5acc4910af02b1919120c59f9a0bac290c780ad1/src/main/java/ru/netology/GameStore.java#L46

# **Метка тестового метода**
https://github.com/Valted-cmd/TeamWork/blob/5acc4910af02b1919120c59f9a0bac290c780ad1/src/test/java/ru/netology/GameStoreTest.java#L58

# **Описание**
Метод addPlayTime класса GameStore не суммирует проигранное игроком время с ранее добавленным временем этого же игрока.

# **Шаги воспроизведения**
В тестовом методе:

1. Создать объект класса GameStore ;
2. Вызвать несколько раз метод addPlayTime объекта GameStore, передать в него имя одного и того же игрока и количество наигранных им часов (в тесте - 12 и 18 часов);
3. Вызвать метод getSumPlayedTime объекта GameStore

# **Ожидаемый результат**
Вывод метода getSumPlayedTime - 30.

# **Фактический результат**
Вывод метода containsGame - 0

# **Скриншот**
![не сумм](https://user-images.githubusercontent.com/67290277/170514062-33992a46-b939-4ffd-963b-3b2528d3b8d9.png)

# **Окружение**

Windows 10
IntelliJ IDEA 2021.3.2 (Community Edition)

**Comment by Dina18013** [comment]
# Метка метода
[https://github.com/Valted-cmd/TeamWork/blob/031b26c82999b73f8f01ab845d1a797fdeefd16b/src/main/java/ru/netology/GameStore.java#L40-L47](url)

Баг исправила. Тест проходит.

# Скриншот
![work14](https://user-images.githubusercontent.com/99754434/171996100-8313e94a-cc42-4bbf-a572-5e6d69e82522.png)
