### ISSUE TITLE
Суммирование общего времени игр выдает неверный результат

### ISSUE THREAD

**Issue by Valted-cmd** [Valted-cmd/TeamWork#7]
# **Метка метода**
https://github.com/Valted-cmd/TeamWork/blob/5acc4910af02b1919120c59f9a0bac290c780ad1/src/main/java/ru/netology/GameStore.java#L75
# **Метка тестового метода**
https://github.com/Valted-cmd/TeamWork/blob/5acc4910af02b1919120c59f9a0bac290c780ad1/src/test/java/ru/netology/GameStoreTest.java#L132
# **Описание**
Метод getSumPlayedTime класса GameStore возвращает неправильный результат при наличии одного или нескольких игроков

# **Шаги воспроизведения**
В тестовом методе:

1. Создать объект класса GameStore ;
2. Вызвать несколько раз метод addPlayTime объекта GameStore, передать в него необходимые параметры: разные имена игроков и разные количества часов, потраченных на игры;
3. Вызвать метод getSumPlayedTime объекта GameStore;

# **Ожидаемый результат**
Вывод метода getSumPlayedTime - Сумма продолжительностей игр всех игроков ( в тесте 80 часов).

# **Фактический результат**
Вывод метода getSumPlayedTime - 0.
# **Скриншот**
![суммирование](https://user-images.githubusercontent.com/67290277/170519109-32e0f16c-95f2-470d-924e-15508b0577d7.png)

# **Окружение**

Windows 10
IntelliJ IDEA 2021.3.2 (Community Edition)

**Comment by Dina18013** [comment]
# Метка метода
[https://github.com/Valted-cmd/TeamWork/blob/031b26c82999b73f8f01ab845d1a797fdeefd16b/src/main/java/ru/netology/GameStore.java#L40-L47](url)

Баг исправила. Тест проходит.

# Скриншот
![work15](https://user-images.githubusercontent.com/99754434/171996152-e22a1aa4-0014-4161-8f60-463df6444c6e.png)
