### ISSUE TITLE
Поиск заигравшегося игрока выдает неправильное значение, когда игроки играли по 0 часов

### ISSUE THREAD

**Issue by Valted-cmd** [Valted-cmd/TeamWork#8]
# **Метка метода**
https://github.com/Valted-cmd/TeamWork/blob/5acc4910af02b1919120c59f9a0bac290c780ad1/src/main/java/ru/netology/GameStore.java#L58

# **Метка тестового метода**
https://github.com/Valted-cmd/TeamWork/blob/5acc4910af02b1919120c59f9a0bac290c780ad1/src/test/java/ru/netology/GameStoreTest.java#L98

# **Описание**
Метод getMostPlayer класса GameStore возвращает неправильный результат, когда игроки играли по 0 часов

# **Шаги воспроизведения**
В тестовом методе:

1. Создать объект класса GameStore ;
2. Вызвать несколько раз метод addPlayTime объекта GameStore, передать в него необходимые параметры: разные имена игроков и 0 часов, потраченных на игры;
3. Вызвать метод getMostPlayer объекта GameStore;

# **Ожидаемый результат**
Вывод метода getMostPlayer- имя первого игрока на шаге 2 ("Maniac").

# **Фактический результат**
Вывод метода getMostPlayer- null.

# **Скриншот**
![0](https://user-images.githubusercontent.com/67290277/170520378-58e98766-7a52-41d5-a0cc-72af7ee4670f.png)

# **Окружение**
Windows 10
IntelliJ IDEA 2021.3.2 (Community Edition)
Скриншот

**Comment by Dina18013** [comment]
# Метка метода
[https://github.com/Valted-cmd/TeamWork/blob/cd0a4797598cee2033a2f95cb395ceb3758dfd8b/src/main/java/ru/netology/GameStore.java#L56-L60](url)

Баг исправила. Тест проходит.
 
# Скриншот
![work16](https://user-images.githubusercontent.com/99754434/171996469-01b303bd-7673-4069-bfd0-51d6ca81e1c5.png)
